@startuml
left to right direction
actor "システム利用者" as usr
rectangle System（必須課題） {
	rectangle 商品表示機能群 {
		usecase "UC01：ログインする" as uc01
		usecase "UC02：商品一覧を表示する" as uc02
		usecase "UC03：商品を検索する" as uc03
	}
	rectangle Cart機能群 as cart{
		usecase "UC04：商品をカートに入れる" as uc04
		usecase "UC05：カートの中を見る" as uc05
		usecase "UC06：カートの商品を削除する" as uc06
	}
	rectangle 商品購入機能群 {
		usecase "UC07：購入者情報を入力する" as uc07
		usecase "UC08：入力した情報を確認する" as uc08
		usecase "UC09：購入処理を実行する" as uc09
	}
}
note right of uc02 {
	【追加課題】
	一覧にカテゴリ名を表示する。
}

usr --> uc01
usr --> uc02
usr --> uc03
usr --> uc04
usr --> uc05
usr --> uc06
usr --> uc07
usr --> uc08
usr --> uc09
@enduml
