@startuml
left to right direction
actor "システム利用者" as usr
rectangle System（追加課題） {
	usecase "UC11：商品一覧を並べ替える" as uc11
	usecase "UC12：商品を価格検索する" as uc12
	usecase "UC13：商品の情報を修正する" as uc13
	usecase "UC14：商品を削除する" as uc14
}

note right of uc11
	並べ替えフィールドは以下の通り：
	　・商品名
	　・価格
	かつ降順・昇順の選択可。
	並べ替えフィールドの値が同じ場合には、それ以外のフィールドで
	の並べ替えはしない。
end note

note right of uc12
	価格の範囲を指定して商品検索する。検索条件は以下の通り：
	・条件-1：価格の範囲下限のみが指定されている場合は、その
	　　　　　下限値以上の価格の商品を表示。
	・条件-2：価格の範囲上限のみが指定されている場合は、その
	　　　　　上限値以下の価格の商品を表示。
	・条件-3：価格の範囲が加減、上限とも指定されている場合は、
	　　　　　その下限値以上上限値以下の価格の商品を表示。
end note

note right of uc13
	商品ID以外のフィールドを修正対象とする。
end note

note right of uc14
	指定された商品を削除することができるものとし、対象商品は
	複数選択できるものとする。
	また、全削除もできるようにする。
end note

usr --> uc11
usr --> uc12
usr --> uc13
usr --> uc14
@enduml
